helloWorld : helloWorld.groovy
	groovyc helloWorld.groovy
	groovy helloWorld

fact : fact.groovy
	groovyc fact.groovy
	groovy fact

loops : p2_loops.groovy
	groovyc p2_loops.groovy
	groovy loops

if : p2_if.groovy
	groovyc p2_if.groovy
	groovy if

switch : p2_switch.groovy
	groovyc p2_switch.groovy
	groovy switch

feature : p2_feature.groovy
	groovyc p2_feature.groovy
	groovy feature