helloWorld : helloWorld.groovy
	groovyc helloWorld.groovy
	groovy helloWorld

fact : fact.groovy
	groovyc fact.groovy
	groovy fact

loops : p2_loops.groovy
	groovyc p2_loops.groovy
	groovy loops

if : p2_if.groovy
	groovyc p2_if.groovy
	groovy if

switch : p2_switch.groovy
	groovyc p2_switch.groovy
	groovy switch

feature : p2_feature.groovy
	groovyc p2_feature.groovy
	groovy feature

boolean : p3_boolean.groovy
	groovyc p3_boolean.groovy
	groovy p3_boolean

string : p3_String.groovy
	groovyc p3_String.groovy
	groovy p3_String

char : p3_char.groovy
	groovyc p3_char.groovy
	groovy p3_char

lists : p3_lists.groovy
	groovyc p3_lists.groovy
	groovy p3_lists

arrays : p3_arrays.groovy
	groovyc p3_arrays.groovy
	groovy p3_arrays

maps : p3_maps.groovy
	groovyc p3_maps.groovy
	groovy p3_maps

ranges : p3_range.groovy
	groovyc p3_range.groovy
	groovy p3_range

ints : p3_int.groovy
	groovyc p3_int.groovy
	groovy p3_int

float : p3_float.groovy
	groovyc p3_float.groovy
	groovy p3_float

failures : p3_failures.groovy
	groovyc p3_failures.groovy
	groovy p3_failures

program : p3_program.groovy
	groovyc p3_program.groovy
	groovy p3_program

classes : p4_classes.groovy
	groovyc p4_classes.groovy
	groovy p4_classes

closures : p4_closures.groovy
	groovyc p4_closures.groovy
	groovy p4_closures

methods : p4_methods.groovy
	groovyc p4_methods.groovy
	groovy p4_methods

.PHONY: clean
clean:
	rm *.class
